sudo: required
language: java
jdk: openjdk8
services: docker

before_install: docker pull nfcore/exoseq:latest

install:
  # Install Nextflow
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Install nf-core/tools
  - git clone https://github.com/nf-core/tools.git /tmp/nf-core-tools
  - cd /tmp/nf-core-tools
  - pip install --user -e .
  # Make test directories
  - mkdir ${TRAVIS_BUILD_DIR}/tests
  - cd ${TRAVIS_BUILD_DIR}/tests


env:
  - NXF_VER=0.30.2
  - ''

script:
  # Lint the pipeline code
  - "nf-core lint ${TRAVIS_BUILD_DIR}"
  # Run the pipeline
  # Need to download metafiles and kitfiles first, unpack these manually
  - sh ${TRAVIS_BUILD_DIR}/scripts/fetchMetaFiles.sh
  - ls -l
  - nextflow run ${TRAVIS_BUILD_DIR} -profile test,docker --metafiles ./ --kitfiles kits/ --genome 'smallGRCh37'
